drop table if exists mixes CASCADE;
drop table if exists tracks CASCADE; 
create table mixes (
id bigint generated by default as identity, 
mix_length time not null, 
mix_name varchar(255) not null, 
primary key (id)
);



create table tracks (
id bigint generated by default as identity, 
track_artist varchar(255) not null, 
track_length time not null, 
track_name varchar(255) not null, 
mixes_id bigint, primary key (id)
);

alter table tracks add constraint FKd03qt5ln0y9cjvbwhn3330mf1 foreign key (mixes_id) references mixes on delete cascade;